SELECT 
    emp.FIRST_NAME,
    emp.LAST_NAME,
    emp.SALARY,
    dep.DEPARTMENT_NAME,
    job.JOB_TITLE
FROM HR.EMPLOYEES emp
LEFT JOIN HR.DEPARTMENTS dep 
    ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT JOIN HR.JOBS job 
    ON emp.JOB_ID = job.JOB_ID
WHERE emp.SALARY > 0;