SELECT 
    emp.FIRST_NAME,
    emp.LAST_NAME,
    emp.SALARY,
    dep.DEPARTMENT_NAME,
    loc.CITY,
    loc.STATE_PROVINCE,
    ctr.COUNTRY_NAME,
    reg.REGION_NAME
FROM HR.EMPLOYEES emp
LEFT JOIN HR.DEPARTMENTS dep 
    ON emp.DEPARTMENT_ID = dep.DEPARTMENT_ID
LEFT JOIN HR.LOCATIONS loc 
    ON dep.LOCATION_ID = loc.LOCATION_ID
LEFT JOIN HR.COUNTRIES ctr 
    ON loc.COUNTRY_ID = ctr.COUNTRY_ID
LEFT JOIN HR.REGIONS reg 
    ON ctr.REGION_ID = reg.REGION_ID
WHERE reg.REGION_NAME IS NOT NULL;